spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/oser
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  
